### ISSUE TITLE
Change orders modification

### ISSUE THREAD

**Issue by CannibalKush** [zkrige/freelancer_contract#5]
"If Developer cannot or chooses not to accept the change order, then Customer may elect to terminate the agreement."

It seems that no provision is stipulated to provide payment if the Customer chooses to terminate the agreement when presented with increased costs due to a change request. 

Am I mistaken?

**Comment by zkrige** [comment]
I think 15.1 deals with it. Perhaps a good idea would be to put something in that clause which points to this clause

15.1 (d) **Termination for no Cause.** If Customer chooses to terminate contract early for no good cause, there shall be a 33% of the total project cost penalty fee paid to Developer.

**Comment by CannibalKush** [comment]
Yeah you're totally right, in fact I believe the scenario I've outlined should be caught by 15.1(c). I'm actually satisfied that no changes to the text of the agreement is needed for this.

Feel free to close the issue.

**Comment by zkrige** [comment]
Cool - thanks for the critique anyways. Its always good to have more eyes on this
